# Generated by Django 4.2 on 2023-04-14 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Empty', 'Empty'), ('Token Generated', 'Token Generated'), ('Token Verified', 'Token Verified')], default='Empty', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electionName', models.CharField(max_length=50, unique=True)),
                ('electionDate', models.DateField()),
                ('electionTimeStart', models.TimeField()),
                ('electionTimeEnd', models.TimeField()),
                ('electionStatus', models.BooleanField(default=False)),
                ('numberOfCandidates', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('entryNumber', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otpGenerated', models.CharField(max_length=4)),
                ('otpVerified', models.BooleanField(default=False)),
                ('voteCasted', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electorate.election')),
                ('entryNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electorate.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_rid', models.DecimalField(decimal_places=0, max_digits=50)),
                ('C_v', models.DecimalField(decimal_places=0, max_digits=50)),
                ('rid', models.DecimalField(decimal_places=0, max_digits=50)),
                ('v', models.DecimalField(decimal_places=0, max_digits=50)),
                ('r_rid', models.DecimalField(decimal_places=0, max_digits=50)),
                ('r_v', models.DecimalField(decimal_places=0, max_digits=50)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electorate.election')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.DecimalField(decimal_places=0, max_digits=50)),
                ('r_rid', models.DecimalField(decimal_places=0, max_digits=50)),
                ('u', models.DecimalField(decimal_places=0, max_digits=50)),
                ('r_u', models.DecimalField(decimal_places=0, max_digits=50)),
                ('otp', models.CharField(max_length=4)),
                ('validFrom', models.DateTimeField()),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electorate.booth')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electorate.voter')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j', models.IntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electorate.election', to_field='electionName')),
                ('entryNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electorate.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(fields=('entryNumber', 'election'), name='unique_electorate'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('entryNumber', 'election'), name='unique_candidate'),
        ),
    ]
