# Generated by Django 4.2 on 2023-04-20 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electorate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokentootp',
            fields=[
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='electorate.token', unique=True)),
                ('otp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electorate.otp')),
            ],
        ),
    ]
