# Generated by Django 4.2 on 2023-04-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electorate', '0002_tokentootp_delete_otptotoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tokentootp',
            new_name='OtpToToken',
        ),
    ]
