# Generated by Django 4.2 on 2023-04-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electorate', '0005_rename_c_rid_vote_c_ridx_vote_c_ridy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='rid',
            field=models.DecimalField(decimal_places=2, max_digits=300),
        ),
        migrations.AlterField(
            model_name='vote',
            name='v',
            field=models.IntegerField(default=-1),
        ),
    ]
